### ISSUE TITLE
Data Visualization of Twitter words

### ISSUE THREAD

**Issue by ninjapanzer** [Westmoreland-Open-Hack/Brainstorming#9]
I have a little toy I built which counts words from twitter sample api
https://github.com/ninjapanzer/natural-language-node

I would love to visualize this in some way and I need help!

**Comment by pearvert** [comment]
As I said after the meeting I would love to assist you with visualizing the Twitter data.  Just give me some further details to review when you have them and we can move to the next step.

**Comment by ninjapanzer** [comment]
What would be most useful to you. Tabular data to start with. I would be happy to build something that displays the data to the web browser as its coming in

**Comment by pearvert** [comment]
Here's a few questions to mull over before we being.

Do you want to show data over time? Will your data be in categories. Are you looking for at a specific item. And mostly, are you going for an Explanatory or Exploratory visual.

Many time what you think you want to visualize from the start ends up on the cutting room floor after a review of what you see in the data. It can be a tricky and complex start process but it's better to review and plan before rushing in and then having to start again. Believe me, Been there—Done that.

We could meet up one evening for a 1:1 to discuss it. You could sent me a small sample of your data and some thoughts on what you'd like to show. When I see any data, I know how I'd like to visualize it but I need to know what you're thinking of.

Later,

**Comment by ninjapanzer** [comment]
Superseded By MVP outline #11 so closing
